-- ============================================================================
-- TARGET V1 — 0058 PURCHASE ATTACHMENT STORAGE (ADR-008)
-- Authority: .planning/adr/ADR-008_PURCHASE_ATTACHMENT_STORAGE.md (ACCEPTED, owner decision D-F27D-1)
--            RLS_IMPLEMENTATION_SPEC_V1.md §7 purchase attachments storage perimeter [ADR-008]
--            RPC_CONTRACTS_V1.md 13 register_purchase (attachment objects precede the call) [ADR-008]
--            POSTGRES_SCHEMA_SPEC_V1.md purchase_attachment.storage_path [ADR-008]
--
-- Adds:
--   * the PRIVATE Storage bucket `purchase-attachments`: 10 MB per object, MIME allowlist
--     application/pdf, image/jpeg, image/png, image/webp;
--   * three storage.objects policies for `authenticated`, confined to that bucket:
--       SELECT / DELETE: current_app_role() = 'ADMIN';
--       INSERT:          current_app_role() = 'ADMIN' AND the first path segment is the uploader's auth.uid()
--                        (object key `<auth-user-id>/<uuid>.<ext>`, generated by the frontend).
--     No UPDATE policy: an uploaded object is never overwritten or moved.
--     No policy for anon; OPERATOR gets false; nothing applies to any other bucket.
--
-- The role comes from the single existing authority current_app_role() (RLS spec §2). It raises for a
-- caller without an active profile, so it is evaluated inside CASE only for rows of this bucket: CASE
-- evaluates the bucket test first, and every other bucket's rows get `false` without calling it.
--
-- No public table, column, function or grant changes: the SECURITY DEFINER set stays at 62,
-- purchase_attachment keeps its metadata columns, register_purchase is unchanged.
-- ============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('purchase-attachments', 'purchase-attachments', false, 10485760,
        ARRAY['application/pdf', 'image/jpeg', 'image/png', 'image/webp']);

CREATE POLICY purchase_attachments_admin_select ON storage.objects
  FOR SELECT TO authenticated
  USING (CASE WHEN bucket_id = 'purchase-attachments' THEN public.current_app_role() = 'ADMIN' ELSE false END);

CREATE POLICY purchase_attachments_admin_insert ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (CASE WHEN bucket_id = 'purchase-attachments'
                   THEN public.current_app_role() = 'ADMIN' AND (storage.foldername(name))[1] = auth.uid()::TEXT
                   ELSE false END);

CREATE POLICY purchase_attachments_admin_delete ON storage.objects
  FOR DELETE TO authenticated
  USING (CASE WHEN bucket_id = 'purchase-attachments' THEN public.current_app_role() = 'ADMIN' ELSE false END);
