-- ETAPA 2: Módulo de Caja (Finanzas)

-- Enum for movimiento tipo
create type movimiento_tipo as enum ('ingreso', 'egreso');

-- Enum for forma de pago
create type forma_pago_type as enum ('efectivo', 'mercadopago', 'echeq', 'cheque');

-- Enum for movimiento estado
create type movimiento_estado as enum ('pendiente', 'confirmado', 'cancelado');

-- Enum for cheque estado
create type cheque_estado as enum ('emitido', 'cobrado', 'rechazado', 'cancelado');

-- Tabla movimientos_caja
create table movimientos_caja (
  id bigint primary key generated by default as identity,
  tipo movimiento_tipo not null,
  concepto text not null,
  monto numeric(10,2) not null,
  forma_pago forma_pago_type not null,
  fecha_operacion date not null default current_date,
  fecha_pago date not null default current_date,
  estado movimiento_estado not null default 'pendiente',
  cuenta_origen text,
  cuenta_destino text,
  vinculado_a text, -- 'pedido', 'pago', 'ninguno'
  vinculado_id bigint,
  notas text,
  creado_por uuid references perfiles(id),
  creado_en timestamptz default now(),
  actualizado_en timestamptz default now()
);

-- Tabla cheques
create table cheques (
  id bigint primary key generated by default as identity,
  numero text not null unique,
  banco text not null,
  monto numeric(10,2) not null,
  fecha_emision date not null,
  fecha_vencimiento date not null,
  girador text not null,
  estado cheque_estado not null default 'emitido',
  movimiento_caja_id bigint references movimientos_caja(id),
  notas text,
  creado_por uuid references perfiles(id),
  creado_en timestamptz default now(),
  actualizado_en timestamptz default now()
);

-- Tabla comisiones
create table comisiones (
  id bigint primary key generated by default as identity,
  concepto text not null,
  monto numeric(10,2) not null,
  porcentaje numeric(5,2), -- ej: 3.5 para 3.5%
  base_monto numeric(10,2), -- monto sobre el cual se calcula
  fecha_operacion date not null default current_date,
  estado movimiento_estado not null default 'pendiente',
  movimiento_caja_id bigint references movimientos_caja(id),
  notas text,
  creado_por uuid references perfiles(id),
  creado_en timestamptz default now(),
  actualizado_en timestamptz default now()
);

-- Indexes
create index idx_movimientos_caja_fecha_operacion on movimientos_caja(fecha_operacion desc);
create index idx_movimientos_caja_forma_pago on movimientos_caja(forma_pago);
create index idx_movimientos_caja_tipo on movimientos_caja(tipo);
create index idx_movimientos_caja_estado on movimientos_caja(estado);
create index idx_movimientos_caja_vinculado on movimientos_caja(vinculado_a, vinculado_id);
create index idx_cheques_fecha_vencimiento on cheques(fecha_vencimiento);
create index idx_cheques_estado on cheques(estado);
create index idx_comisiones_fecha_operacion on comisiones(fecha_operacion desc);

-- Updated_at triggers
create or replace function actualizar_timestamp_movimientos_caja()
returns trigger as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$ language plpgsql;

create trigger trigger_actualizar_timestamp_movimientos_caja
before update on movimientos_caja
for each row
execute function actualizar_timestamp_movimientos_caja();

create or replace function actualizar_timestamp_cheques()
returns trigger as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$ language plpgsql;

create trigger trigger_actualizar_timestamp_cheques
before update on cheques
for each row
execute function actualizar_timestamp_cheques();

create or replace function actualizar_timestamp_comisiones()
returns trigger as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$ language plpgsql;

create trigger trigger_actualizar_timestamp_comisiones
before update on comisiones
for each row
execute function actualizar_timestamp_comisiones();
