-- ============================================================================
-- COMPACT MONTHLY VALIDATION: One-line result per month
-- File: validate_liberaciones_month_COMPACT.sql
-- Status: READ-ONLY
-- Edit config section for each month (month_start, month_end, expected values)
-- ============================================================================

SELECT
  '2026-04' as month,
  (SELECT COUNT(*) FROM ledger_entry WHERE account_id = 1054315166 AND DATE(occurred_at AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date) as ledger_count,
  (SELECT COALESCE(SUM(balance_impact), 0) FROM ledger_entry WHERE account_id = 1054315166 AND DATE(occurred_at AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date) as ledger_net,
  -914712.70::NUMERIC(15,2) as expected_ledger_net,
  (SELECT COUNT(DISTINCT msr.id) FROM mp_source_record msr INNER JOIN mp_movement_source_link mmsl ON msr.id = mmsl.source_record_id INNER JOIN mp_financial_movement mfm ON mmsl.financial_movement_id = mfm.id WHERE msr.source_type = 'liberaciones' AND msr.raw_data->>'DESCRIPTION' = 'payment' AND mfm.account_id = 1054315166 AND DATE(mfm.transaction_date AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date) as payment_sources,
  (SELECT COUNT(DISTINCT msr.id) FROM mp_source_record msr INNER JOIN mp_movement_source_link mmsl ON msr.id = mmsl.source_record_id INNER JOIN mp_financial_movement mfm ON mmsl.financial_movement_id = mfm.id WHERE msr.source_type = 'liberaciones' AND msr.raw_data->>'DESCRIPTION' = 'payout' AND mfm.account_id = 1054315166 AND DATE(mfm.transaction_date AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date) as payout_sources,
  (SELECT COUNT(DISTINCT mfm.id) FROM mp_source_record msr INNER JOIN mp_movement_source_link mmsl ON msr.id = mmsl.source_record_id INNER JOIN mp_financial_movement mfm ON mmsl.financial_movement_id = mfm.id WHERE msr.source_type = 'liberaciones' AND msr.raw_data->>'DESCRIPTION' = 'payout' AND mfm.account_id = 1054315166 AND DATE(mfm.transaction_date AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date) as payout_fm_count,
  (SELECT COUNT(DISTINCT mfm.id) FROM mp_source_record msr INNER JOIN mp_movement_source_link mmsl ON msr.id = mmsl.source_record_id INNER JOIN mp_financial_movement mfm ON mmsl.financial_movement_id = mfm.id INNER JOIN ledger_entry le ON mfm.id = le.financial_movement_id WHERE msr.source_type = 'liberaciones' AND msr.raw_data->>'DESCRIPTION' = 'payout' AND mfm.account_id = 1054315166 AND DATE(mfm.transaction_date AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date) as payout_ledger_count,
  (SELECT SUM(DISTINCT settlement_amount) FROM (SELECT DISTINCT mfm.settlement_amount FROM mp_source_record msr INNER JOIN mp_movement_source_link mmsl ON msr.id = mmsl.source_record_id INNER JOIN mp_financial_movement mfm ON mmsl.financial_movement_id = mfm.id WHERE msr.source_type = 'liberaciones' AND msr.raw_data->>'DESCRIPTION' = 'payout' AND mfm.account_id = 1054315166 AND DATE(mfm.transaction_date AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date) payout_amounts) as payout_net,
  -8587808.53::NUMERIC(15,2) as expected_payout_net,
  (SELECT COUNT(*) FROM mp_financial_movement WHERE account_id = 1054315166 AND needs_review = TRUE) as total_needs_review,
  (SELECT COUNT(*) FROM mp_financial_movement WHERE account_id = 1054315166 AND needs_review = TRUE AND DATE(transaction_date AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date) as month_needs_review,
  (SELECT COUNT(*) FROM (SELECT financial_movement_id, COUNT(*) as le_count FROM ledger_entry WHERE account_id = 1054315166 AND DATE(occurred_at AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date GROUP BY financial_movement_id HAVING COUNT(*) > 1) dup) as duplicate_ledger_count,
  (SELECT COUNT(*) FROM (SELECT financial_movement_id, source_record_id, COUNT(*) as link_count FROM mp_movement_source_link mmsl WHERE EXISTS (SELECT 1 FROM mp_source_record msr WHERE msr.id = mmsl.source_record_id AND msr.source_type = 'liberaciones') AND EXISTS (SELECT 1 FROM mp_financial_movement mfm WHERE mfm.id = mmsl.financial_movement_id AND mfm.account_id = 1054315166 AND DATE(mfm.transaction_date AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date) GROUP BY financial_movement_id, source_record_id HAVING COUNT(*) > 1) dup_links) as duplicate_liberaciones_links,
  CASE
    WHEN (SELECT COALESCE(SUM(balance_impact), 0) FROM ledger_entry WHERE account_id = 1054315166 AND DATE(occurred_at AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date) = -914712.70::NUMERIC(15,2)
      AND (SELECT SUM(DISTINCT settlement_amount) FROM (SELECT DISTINCT mfm.settlement_amount FROM mp_source_record msr INNER JOIN mp_movement_source_link mmsl ON msr.id = mmsl.source_record_id INNER JOIN mp_financial_movement mfm ON mmsl.financial_movement_id = mfm.id WHERE msr.source_type = 'liberaciones' AND msr.raw_data->>'DESCRIPTION' = 'payout' AND mfm.account_id = 1054315166 AND DATE(mfm.transaction_date AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date) payout_amounts) = -8587808.53::NUMERIC(15,2)
      AND (SELECT COUNT(*) FROM mp_financial_movement WHERE account_id = 1054315166 AND needs_review = TRUE) = 2
      AND (SELECT COUNT(*) FROM (SELECT financial_movement_id, COUNT(*) as le_count FROM ledger_entry WHERE account_id = 1054315166 AND DATE(occurred_at AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date GROUP BY financial_movement_id HAVING COUNT(*) > 1) dup) = 0
      AND (SELECT COUNT(*) FROM (SELECT financial_movement_id, source_record_id, COUNT(*) as link_count FROM mp_movement_source_link mmsl WHERE EXISTS (SELECT 1 FROM mp_source_record msr WHERE msr.id = mmsl.source_record_id AND msr.source_type = 'liberaciones') AND EXISTS (SELECT 1 FROM mp_financial_movement mfm WHERE mfm.id = mmsl.financial_movement_id AND mfm.account_id = 1054315166 AND DATE(mfm.transaction_date AT TIME ZONE 'America/Argentina/Buenos_Aires') BETWEEN '2026-04-01'::date AND '2026-04-30'::date) GROUP BY financial_movement_id, source_record_id HAVING COUNT(*) > 1) dup_links) = 0
      THEN 'PASS'
    ELSE 'FAIL'
  END as status;
